spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

#本地文件存储配置
files:
    host:  http://localhost:8080 # 图片请求地址
    path:  static # 文件保存路径
    absolutePath: D:/workspaces/mall/mall-admin/src/main/resources/static/ #文件保存的绝对路径
    images:
      prefix: images # 上传图片路径前缀
