spring:
  datasource:
    url: jdbc:mysql://172.17.204.82:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234_Qwer
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

#本地文件存储配置
files:
  host:  http://39.107.38.88:8080/mall-admin # 图片请求地址
  path:  static # 文件保存路径
  absolutePath: /arlin/tomcat-9.0.27/webapps/mall-admin/WEB-INF/classes/static/ #文件保存的绝对路径
  images:
    prefix: images # 上传图片路径前缀
logging:
  path: /var/logs #配置日志生成路径
